# config context path to "/" by setting an empty string
server:
  contextPath: /api

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    data: "classpath*:data.sql"
    database-platform: org.hibernate.dialect.H2Dialect
    h2.console.enabled: true      

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG